const { GoogleGenerativeAI } = require('@google/generative-ai');
const { Octokit } = require('@octokit/rest');

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

async function reviewPR() {
  const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
  const prNumber = parseInt(process.env.PR_NUMBER);

  // Get PR diff
  const { data: diff } = await octokit.pulls.get({
    owner,
    repo,
    pull_number: prNumber,
    mediaType: { format: 'diff' }
  });

  // Get PR details
  const { data: pr } = await octokit.pulls.get({
    owner,
    repo,
    pull_number: prNumber
  });

  // Generate review using Gemini
  const model = genAI.getGenerativeModel({ model: process.env.MODEL });
  
  const prompt = `You are an expert code reviewer. Please review the following pull request:

Title: ${pr.title}
Description: ${pr.body || 'No description provided'}

Diff:
\`\`\`diff
${diff}
\`\`\`

Please provide:
1. A summary of the changes
2. Potential issues or bugs
3. Security concerns
4. Performance considerations
5. Code quality suggestions
6. Best practices recommendations

Format your response in markdown.`;

  const result = await model.generateContent(prompt);
  const response = await result.response;
  const reviewText = response.text();

  // Post review comment
  await octokit.issues.createComment({
    owner,
    repo,
    issue_number: prNumber,
    body: `## 🤖 Google Gemini Code Review\n\n${reviewText}\n\n---\n*This review was generated by Google Gemini AI*`
  });

  console.log('Review posted successfully');
  console.log(`::set-output name=comment::${reviewText}`);
}

reviewPR().catch(error => {
  console.error('Error performing review:', error);
  process.exit(1);
});
