#!/bin/bash

# Network Configuration Script
# Configure wired network connections to use WireGuard VPN

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
VPN_INTERFACE="${1:-wg0}"
WIRED_INTERFACE="${2:-auto}"

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}Error: This script must be run as root (use sudo)${NC}"
   exit 1
fi

# Function to detect wired interface
detect_wired_interface() {
    # Try to find the primary wired interface
    local interface=$(ip -o link show | grep -v "lo\|wg\|tun\|tap\|docker\|veth\|br-" | grep "state UP" | head -1 | awk -F': ' '{print $2}')
    
    if [ -z "$interface" ]; then
        # If no UP interface, try to find any wired interface
        interface=$(ip -o link show | grep -E "eth|enp|eno" | head -1 | awk -F': ' '{print $2}')
    fi
    
    echo "$interface"
}

# Function to get current DNS servers
get_current_dns() {
    if [ -f /etc/resolv.conf ]; then
        grep "^nameserver" /etc/resolv.conf | awk '{print $2}' | tr '\n' ' '
    fi
}

# Function to configure DNS to use VPN
configure_dns() {
    echo -e "${YELLOW}Configuring DNS through VPN...${NC}"
    
    # Get DNS from WireGuard config
    local vpn_dns=$(grep "^DNS" /etc/wireguard/$VPN_INTERFACE.conf 2>/dev/null | cut -d'=' -f2 | tr -d ' ' | tr ',' ' ')
    
    if [ -z "$vpn_dns" ]; then
        echo -e "${YELLOW}No DNS configured in VPN config, using defaults${NC}"
        vpn_dns="1.1.1.1 1.0.0.1"
    fi
    
    # Backup current resolv.conf
    if [ ! -f /etc/resolv.conf.backup ]; then
        cp /etc/resolv.conf /etc/resolv.conf.backup
        echo -e "${GREEN}✓ Backed up current DNS configuration${NC}"
    fi
    
    # Configure DNS
    if command -v resolvconf &> /dev/null; then
        # Use resolvconf if available
        echo "nameserver $(echo $vpn_dns | awk '{print $1}')" | resolvconf -a $VPN_INTERFACE
        if [ $(echo $vpn_dns | wc -w) -gt 1 ]; then
            echo "nameserver $(echo $vpn_dns | awk '{print $2}')" | resolvconf -a $VPN_INTERFACE
        fi
        echo -e "${GREEN}✓ DNS configured via resolvconf${NC}"
    else
        # Fallback to direct resolv.conf modification
        cat > /etc/resolv.conf << EOF
# Generated by configure-network.sh for WireGuard VPN
# Backup saved at /etc/resolv.conf.backup
$(for dns in $vpn_dns; do echo "nameserver $dns"; done)
EOF
        echo -e "${GREEN}✓ DNS configured directly${NC}"
    fi
}

# Function to restore DNS
restore_dns() {
    echo -e "${YELLOW}Restoring original DNS configuration...${NC}"
    
    if [ -f /etc/resolv.conf.backup ]; then
        cp /etc/resolv.conf.backup /etc/resolv.conf
        echo -e "${GREEN}✓ DNS configuration restored${NC}"
    else
        echo -e "${YELLOW}No backup found, using system defaults${NC}"
        
        # Try to use systemd-resolved
        if command -v systemd-resolve &> /dev/null || command -v resolvectl &> /dev/null; then
            ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf 2>/dev/null || true
        fi
    fi
    
    if command -v resolvconf &> /dev/null; then
        resolvconf -d $VPN_INTERFACE 2>/dev/null || true
    fi
}

# Function to configure routing
configure_routing() {
    local wired_if="$1"
    
    echo -e "${YELLOW}Configuring routing for VPN...${NC}"
    
    # Check if VPN interface exists
    if ! ip link show $VPN_INTERFACE &> /dev/null; then
        echo -e "${RED}Error: VPN interface $VPN_INTERFACE not found${NC}"
        echo -e "${YELLOW}Make sure VPN is running first${NC}"
        return 1
    fi
    
    # Get VPN gateway if available
    local vpn_gateway=$(ip route show dev $VPN_INTERFACE | grep -oP 'via \K[\d.]+' | head -1)
    
    # Add routing rules to prefer VPN
    echo -e "${GREEN}✓ VPN interface is active${NC}"
    
    # Show current routing table
    echo -e "\n${BLUE}Current routing table:${NC}"
    ip route show | grep -E "default|$VPN_INTERFACE|$wired_if" | head -10
    
    echo ""
    echo -e "${GREEN}✓ Routing configured${NC}"
    echo -e "${YELLOW}Note: WireGuard automatically manages routing based on AllowedIPs${NC}"
}

# Function to show current network configuration
show_config() {
    echo -e "${BLUE}=== Current Network Configuration ===${NC}"
    echo ""
    
    # Wired interface
    if [ "$WIRED_INTERFACE" = "auto" ]; then
        WIRED_INTERFACE=$(detect_wired_interface)
    fi
    
    if [ ! -z "$WIRED_INTERFACE" ]; then
        echo -e "${YELLOW}Wired Interface: $WIRED_INTERFACE${NC}"
        ip addr show $WIRED_INTERFACE 2>/dev/null | grep -E "inet |state" || echo "  Interface not found or down"
    else
        echo -e "${YELLOW}No wired interface detected${NC}"
    fi
    
    echo ""
    
    # VPN interface
    echo -e "${YELLOW}VPN Interface: $VPN_INTERFACE${NC}"
    if ip link show $VPN_INTERFACE &> /dev/null; then
        ip addr show $VPN_INTERFACE | grep -E "inet |state"
    else
        echo "  Interface not active"
    fi
    
    echo ""
    
    # DNS
    echo -e "${YELLOW}DNS Servers:${NC}"
    grep "^nameserver" /etc/resolv.conf 2>/dev/null | awk '{print "  " $2}' || echo "  None configured"
    
    echo ""
    
    # Routing
    echo -e "${YELLOW}Default Routes:${NC}"
    ip route show | grep "^default" | awk '{print "  " $0}'
    
    echo ""
    
    # VPN routes
    if ip link show $VPN_INTERFACE &> /dev/null; then
        echo -e "${YELLOW}VPN Routes:${NC}"
        ip route show dev $VPN_INTERFACE | head -5 | awk '{print "  " $0}'
    fi
}

# Function to apply full VPN configuration
apply_vpn_config() {
    echo -e "${BLUE}=== Configuring Network for VPN ===${NC}"
    echo ""
    
    # Detect wired interface if auto
    if [ "$WIRED_INTERFACE" = "auto" ]; then
        WIRED_INTERFACE=$(detect_wired_interface)
        if [ -z "$WIRED_INTERFACE" ]; then
            echo -e "${YELLOW}Warning: Could not detect wired interface${NC}"
        else
            echo -e "${GREEN}Detected wired interface: $WIRED_INTERFACE${NC}"
        fi
    fi
    
    # Configure DNS
    configure_dns
    
    # Configure routing
    if [ ! -z "$WIRED_INTERFACE" ]; then
        configure_routing "$WIRED_INTERFACE"
    fi
    
    echo ""
    echo -e "${GREEN}=== Configuration Complete ===${NC}"
    echo ""
    
    # Show final configuration
    show_config
}

# Function to remove VPN configuration
remove_vpn_config() {
    echo -e "${BLUE}=== Removing VPN Network Configuration ===${NC}"
    echo ""
    
    # Restore DNS
    restore_dns
    
    echo ""
    echo -e "${GREEN}=== VPN Configuration Removed ===${NC}"
    echo ""
    
    # Show final configuration
    show_config
}

# Display usage
usage() {
    echo "Usage: $0 {apply|remove|show} [vpn-interface] [wired-interface]"
    echo ""
    echo "Commands:"
    echo "  apply      - Configure network to use VPN"
    echo "  remove     - Remove VPN network configuration"
    echo "  show       - Show current network configuration"
    echo ""
    echo "Arguments:"
    echo "  vpn-interface    - WireGuard interface name (default: wg0)"
    echo "  wired-interface  - Wired network interface (default: auto-detect)"
    echo ""
    echo "Examples:"
    echo "  $0 apply                    # Configure with auto-detected interface"
    echo "  $0 apply wg0 eth0           # Configure wg0 VPN with eth0 wired"
    echo "  $0 remove                   # Remove VPN configuration"
    echo "  $0 show                     # Show current configuration"
    echo ""
    echo "Note: This script should be run after the VPN is connected."
    exit 1
}

# Main logic
case "$1" in
    apply)
        VPN_INTERFACE="${2:-wg0}"
        WIRED_INTERFACE="${3:-auto}"
        apply_vpn_config
        ;;
    remove)
        VPN_INTERFACE="${2:-wg0}"
        remove_vpn_config
        ;;
    show)
        VPN_INTERFACE="${2:-wg0}"
        WIRED_INTERFACE="${3:-auto}"
        show_config
        ;;
    *)
        usage
        ;;
esac

exit 0
